version: '3'
volumes:
  mysql_data:
 
services:

  nodechat:
    build:
       context: ./
       dockerfile: Dockerfile.mysql
    volumes:    
     - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: smoot
      MYSQL_USER: "local"
      MYSQL_PASSWORD: "local"
    ports:
     - "127.0.0.1:8083:3306"  # let outside world see 8083
    expose:
     - "3306"    # Let other containers see 3306

  bazaar:
    build: 
       context: ./
       dockerfile: Dockerfile
    depends_on:
     - nodechat
    expose:
     - "8010"
