version: '3'
volumes:
  mysql_data:
 
services:
  nodechat:
    build:
       context: ./
       dockerfile: Dockerfile.mysql
    volumes:    
     - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: smoot
      MYSQL_USER: "local"
      MYSQL_PASSWORD: "local"
    ports:
     - "8089:3306"  # let outside world see 8083
    networks:
    - bazaar
  bazaar:
    build: 
       context: ./
       dockerfile: Dockerfile
    depends_on:
     - nodechat
    ports:
     - "8010:8010"  # let outside world see 8010
    networks:
    - bazaar
networks:
  bazaar:
    driver: bridge
